name: Deploy CLIENT to SERVER

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  APP_NAME: paytract_web
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/paytract_web
  HOST: ${{ secrets.SERVER_HOST }}
  USER: ${{ secrets.SERVER_USER }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image to GHCR
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to SERVER
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
            # Log in to GHCR on SERVER
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Pull the image from GHCR
            docker pull $IMAGE_NAME:latest

            # Navigate to or create app directory
            mkdir -p /home/$USER/paytract_web
            cd /home/$USER/paytract_web

            exit
          EOF

      - name: Copy setup files to SERVER
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml  $USER@$HOST:/home/$USER/paytract_web/

      - name: Final deploy step via SSH
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
            cd /home/$USER/paytract_web

            # Create .env with secrets
            
            echo 'EXAMPLE=secrets.EXAMPLE' >> .env

           
            # Modify docker-compose.yml to use GHCR image
            sed -i "s|^\([[:space:]]*\)build:.*|\\1image: $IMAGE_NAME:latest|" docker-compose.yml
            sed -i '/^[[:space:]]*context:/d; /^[[:space:]]*dockerfile:/d' docker-compose.yml

            docker compose -f docker-compose.yml down || true
            docker compose -f docker-compose.yml up -d

            rm .env
            docker image prune -af
          EOF
